### ISSUE TITLE
Generated fact contains wrong data 

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/ext-jacoco#95]
Below you find an example _Fact_ as currently generated by the app. There seem to be several things not quite right:

* The fact id is '0'. In fact, the code never sets it, meaning all facts will have the same id. What is the intention here? Do we want a random id (aka uuid) in order to identify this particular fact at any time or should the id be some sort of hash over the data, so that two facts which are identical in data get the same id?
* The measurement type says "percent", but we are processing counters. Should the type be "count" or we want to calculate percentages?
* We are only processing the top level aggregated counters in these facts. The underlying jacoco report is more detailed. Is it intentional to only look at the aggregate
*  ' Instructions-Coverage', 'Complexity-Coverage', etc is imo misleading. It is not "coverage" which we record, but lines "covered". That's an issue in the _Fact_ definition though

```yaml
facts:
  - factType: jx.coverage
    id: 0
    measurements:
    - measurementType: percent
      measurementValue: 3
      name: Instructions-Coverage
    - measurementType: percent
      measurementValue: 5
      name: Instructions-Missed
    - measurementType: percent
      measurementValue: 8
      name: Instructions-Total
    - measurementType: percent
      measurementValue: 1
      name: Lines-Coverage
    - measurementType: percent
      measurementValue: 2
      name: Lines-Missed
    - measurementType: percent
      measurementValue: 3
      name: Lines-Total
    - measurementType: percent
      measurementValue: 1
      name: Complexity-Coverage
    - measurementType: percent
      measurementValue: 1
      name: Complexity-Missed
    - measurementType: percent
      measurementValue: 2
      name: Complexity-Total
    - measurementType: percent
      measurementValue: 1
      name: Methods-Coverage
    - measurementType: percent
      measurementValue: 1
      name: Methods-Missed
    - measurementType: percent
      measurementValue: 2
      name: Methods-Total
    - measurementType: percent
      measurementValue: 1
      name: Classes-Coverage
    - measurementType: percent
      measurementValue: 0
      name: Classes-Missed
    - measurementType: percent
      measurementValue: 1
      name: Classes-Total
    name: ""
    original:
      mimetype: application/xml
      tags:
      - jacoco.xml
      url: https://raw.githubusercontent.com/hf-bee/spring-boot-test/gh-pages/jenkins-x/jacoco/hf-bee/spring-boot-test/PR-5/1/target/site/jacoco/jacoco.xml
    statements: []
    tags:
    - jacoco
```

@deanesmith, @pmuir - WDYT?
